stages:
  - Build
  - Scan
  - Run
  - Test

Build:
  stage: Build
  tags:
    - powershell
  script:
    - npm install --force
    - npm run build

Scan:
  stage: Scan
  tags:
    - powershell
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  only:
    - main

Run:
  stage: Run
  tags:
    - powershell
  script:
    - npm install --force
    - npm run start
  only:
    - main
Test:
  stage: Test
  script:
    - npm run test

