# This section defines the different stages your pipeline will have.
# Stages help organize and control the flow of your CI/CD process.
stages:
  - Build  # First stage: Build
  - Test   # Second stage: Test
  - Run    # Third stage: Run

# This job will run in the "Build" stage.
Build_Job:
  stage: Build
  tags:
    - powershell  # This job should run on runners with the "powershell" tag.
  script:
    - npm run build  # Run the "build" command using npm.

# This job will run in the "Test" stage.
Test_Job:
  stage: Test
  tags:
    - powershell  # This job should run on runners with the "powershell" tag.
  script:
    - npm run test  # Run the "test" command using npm.

# This job will run in the "Run" stage.
Run_Job:
  stage: Run
  tags:
    - powershell  # This job should run on runners with the "powershell" tag.
  script:
    - npm run start  # Run the "start" command using npm to start your application.
