stages:
  - Build
  - Packages

Build:
  stage: Build
  tags:
    - shell
  script:
  - npm install -g @angular/cli   # Install Angular CLI globally if not already installed

Package:
  stage: Package
  tags:
    - shell
  script:
    - npm run build
    - mkdir -p artifacts
    - if exist "dist" (xcopy "dist\*" "artifacts" /E /Y) else (echo "No 'dist' directory found")

  artifacts:
    paths:
      - artifacts/
  