stages:
  - Build
  - Scan
  - Run

Build:
  stage: Build
  tags:
    - powershell
  script:
    - npm install --force
    - npm run build

Scan:
  stage: Scan
  tags:
    - powershell
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  only:
    - main

Run:
  stage: Run
  tags:
    - powershell
  script:
    - npm install --force
    - npm run start
  only:
    - main
javascript:
  image: node:latest
  stage: test
  before_script:
    - 'yarn global add jest'
    - 'yarn add --dev jest-junit'
  script:
    - 'jest --ci --reporters=default --reporters=jest-junit'
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

