stages:
  - Build

Build:
  stage: Build
  tags:
    - shell
  script:
    - npm run build
    - mkdir -p artifacts
    - if exist "dist" (xcopy "dist\*" "artifacts" /E /Y) else (echo "No 'dist' directory found")
  artifacts:
    paths:
      - artifacts/
  