stages:
    - Build
    - Test
    - Run
Build_Job:
    stage: Build
    tags:
        - powershell
    script:
        npm install
        npm run build
Test_Job:
    stage: Test
    tags:
        - powershell
    script:
        npm run test

Run_Job: 
    stage: Run
    tags:
        - powershell
    script:
        npm run start