# This is the name of the GitLab CI/CD pipeline.
stages:
  - install
  - build

# Define jobs for each stage.
install:
  stage: install
  tags:
    - shell
  script:
    - npm install --force

build:
  stage: build
  tags:
    - shell
  script:
    - npm run build
