# This is the name of the GitLab CI/CD pipeline.
stages:
  - install
  - build

# Define jobs for each stage.
install:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build
