image: node:latest

stages:
  - build
  - run

# Job's name
first-job:
  # Define stage
  stage: build
  # What to run on the job.
  tags:
    - shell
  script:
    - npm install --force
  artifacts:
    paths:
      - node_modules

second-job:
  stage: run
  tags: 
    - shell
  script:
    - npm run build
  artifacts:
    paths:
      - node_modules/
