apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  labels:
    app: cart
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: ganesharavind124/anacart:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: NodePort
  selector:
    app: cart
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32765
