apiVersion: apps/v1
kind: Deployment
metadata:
  name: anacart-deployment
  labels:
    app: anacart
spec:
  replicas: 3
  selector:
    matchLabels:
      app: anacart
  template:
    metadata:
      labels:
        app: anacart
    spec:
      containers:
      - name: anacart
        image: ganesharavind124/anacart:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: anacartservice
spec:
  type: NodePort
  selector:
    app: anacart
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 32767

